table dim_province
	lineageTag: 65cdda8b-9909-4399-95f7-d41f856b418b

	measure 'Total Rainfall (mm)' = SUM('mart_weather_daily'[rainfall_mm])
		lineageTag: d647f7ac-3fe7-43b4-9bce-b49739e5f372

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Heavy Rain Days' = CALCULATE(COUNTROWS('mart_weather_daily'), 'mart_weather_daily'[rainfall_mm] >= 35.1)
		formatString: 0
		lineageTag: 615f6339-0415-4327-afe9-039301851ec5

	measure 'Very Heavy Rain Days' = CALCULATE(COUNTROWS('mart_weather_daily'), 'mart_weather_daily'[rainfall_mm] >= 90.1)
		formatString: 0
		lineageTag: fbe30962-d86d-4aae-ab6e-deb6106a15fb

	measure 'Rainfall per point (mm)' = DIVIDE(SUM('mart_weather_daily'[rainfall_mm]), DISTINCTCOUNT('dim_province'[province_id]))
		lineageTag: 8d28a9f5-d477-4020-9cc5-85bf662e2fa1

	measure 'Heavy Days per point' = DIVIDE([Heavy Rain Days], DISTINCTCOUNT('dim_province'[province_id]))
		lineageTag: fd5098d1-f85c-4bb8-a216-1921bbda4947

	measure 'Very Heavy Days per point' = DIVIDE([Very Heavy Rain Days], DISTINCTCOUNT('dim_province'[province_id]))
		lineageTag: d73fe0cb-9106-4df5-bf6c-fb8f6f73ab6e

	measure 'Average Temperature (C)' = AVERAGE('mart_weather_daily'[average_temperature_c])
		lineageTag: 80e94415-81be-4520-af7f-69eea1429bd1

	measure 'Average Humidity (%)' = AVERAGE('mart_weather_daily'[average_humidity_pct])
		lineageTag: b4fca8b0-112f-4885-a5b4-c8d84040cb44

	measure 'Average Daily Max Wind (km/h)' = AVERAGE('mart_weather_daily'[maximum_wind_kmh])
		lineageTag: 4ad3a1e8-1e10-435a-a24b-a59d6458b018

	column province_id
		dataType: int64
		formatString: 0
		lineageTag: 57c92852-f4ef-4250-8724-6d8c1334553b
		summarizeBy: none
		sourceColumn: province_id

		annotation SummarizationSetBy = Automatic

	column province_name
		dataType: string
		lineageTag: 35ed8178-7d7b-46d8-bc98-16557aeb7272
		summarizeBy: none
		sourceColumn: province_name

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 9962dd2b-7b53-42c6-9490-0b04725c2d5b
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 176734da-9f65-430a-9d67-ae8e1c855cff
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_province = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("R:\powerbi\export\dim_province.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"province_id", Int64.Type}, {"province_name", type text}, {"latitude", type number}, {"longitude", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
